import json
import random
import os

# --- PALPITE (1000+ items) ---
palpite = []
# Base facts
base_palpite = [
    {"question": "Quantos ossos tem um adulto humano?", "answer": 206},
    {"question": "Quantos dentes tem um adulto humano?", "answer": 32},
    {"question": "Qual a altura do aro de basquete em cm?", "answer": 305},
    {"question": "Quantos dias há em um ano bissexto?", "answer": 366},
    {"question": "Quantos graus tem um círculo completo?", "answer": 360}
]
palpite.extend(base_palpite)

# Procedural generation for Palpite
for i in range(2, 151):
    palpite.append({"question": f"Quantos meses existem em {i} anos?", "answer": i * 12})
    palpite.append({"question": f"Quantos dias existem em {i} semanas?", "answer": i * 7})
    palpite.append({"question": f"Quantas horas tem {i} dias?", "answer": i * 24})

for i in range(1, 151):
    palpite.append({"question": f"Qual o resultado de {i} multiplicado por 15?", "answer": i * 15})
    palpite.append({"question": f"Qual o resultado de {i} multiplicado por 25?", "answer": i * 25})
    palpite.append({"question": f"Qual o resultado de {i} multiplicado por 50?", "answer": i * 50})
    palpite.append({"question": f"Quantos centímetros existem em {i} metros?", "answer": i * 100})

idx = 0
while len(palpite) < 1100:
    idx += 1
    palpite.append({"question": f"Qual é a raiz quadrada de {idx * idx}?", "answer": idx})


# --- DUVIDO (1300 items) ---
duvido = {
  "temas_duvido_duplas": [
    "Animais cujo nome começa com vogal",
    "Animais cujo nome começa com consoante",
    "Animais cujo nome tem mais de 8 letras",
    "Animais cujo nome tem menos de 5 letras",
    "Animais cujo nome tem exatamente duas sílabas",
    "Animais cujo nome termina com a letra A",
    "Animais cujo nome termina com a letra O",
    "Animais cujo nome contém a letra Z",
    "Animais cujo nome contém a letra C",
    "Animais cujo nome tem acento gráfico",
    "Animais cujo nome é uma palavra composta",
    "Animais que são (ou podem ser) predominantemente vermelhos",
    "Animais que são (ou podem ser) predominantemente verdes",
    "Animais que são (ou podem ser) predominantemente azuis",
    "Animais que são (ou podem ser) predominantemente amarelos",
    "Animais que são (ou podem ser) predominantemente brancos",
    "Animais que são (ou podem ser) predominantemente pretos",
    "Animais de origem ou fabricação brasileira",
    "Animais de origem ou fabricação europeia",
    "Animais de origem ou fabricação asiática",
    "Animais de origem ou fabricação norte-americana",
    "Animais encontrados no Brasil",
    "Animais que vivem ou crescem na água",
    "Animais que vivem ou crescem em florestas",
    "Animais considerados grandes ou pesados",
    "Animais considerados pequenos ou leves",
    "Animais de estimação cujo nome começa com vogal",
    "Animais de estimação cujo nome começa com consoante",
    "Animais de estimação cujo nome tem mais de 8 letras",
    "Animais de estimação cujo nome tem menos de 5 letras",
    "Animais de estimação cujo nome tem exatamente duas sílabas",
    "Animais de estimação cujo nome termina com a letra A",
    "Animais de estimação cujo nome termina com a letra O",
    "Animais de estimação cujo nome contém a letra Z",
    "Animais de estimação cujo nome contém a letra C",
    "Animais de estimação cujo nome tem acento gráfico",
    "Animais de estimação cujo nome é uma palavra composta",
    "Animais de estimação que são (ou podem ser) predominantemente vermelhos",
    "Animais de estimação que são (ou podem ser) predominantemente verdes",
    "Animais de estimação que são (ou podem ser) predominantemente azuis",
    "Animais de estimação que são (ou podem ser) predominantemente amarelos",
    "Animais de estimação que são (ou podem ser) predominantemente brancos",
    "Animais de estimação que são (ou podem ser) predominantemente pretos",
    "Animais de estimação considerados grandes ou pesados",
    "Animais de estimação considerados pequenos ou leves",
    "Animais selvagens cujo nome começa com vogal",
    "Animais selvagens cujo nome começa com consoante",
    "Animais selvagens cujo nome tem mais de 8 letras",
    "Animais selvagens cujo nome tem menos de 5 letras",
    "Animais selvagens cujo nome tem exatamente duas sílabas",
    "Animais selvagens cujo nome termina com a letra A",
    "Animais selvagens cujo nome termina com a letra O",
    "Animais selvagens cujo nome contém a letra Z",
    "Animais selvagens cujo nome contém a letra C",
    "Animais selvagens cujo nome tem acento gráfico",
    "Animais selvagens cujo nome é uma palavra composta",
    "Animais selvagens que são (ou podem ser) predominantemente vermelhos",
    "Animais selvagens que são (ou podem ser) predominantemente verdes",
    "Animais selvagens que são (ou podem ser) predominantemente azuis",
    "Animais selvagens que são (ou podem ser) predominantemente amarelos",
    "Animais selvagens que são (ou podem ser) predominantemente brancos",
    "Animais selvagens que são (ou podem ser) predominantemente pretos",
    "Animais selvagens encontrados no Brasil",
    "Animais selvagens que vivem ou crescem na água",
    "Animais selvagens que vivem ou crescem em florestas",
    "Animais selvagens considerados grandes ou pesados",
    "Animais selvagens considerados pequenos ou leves",
    "Aves cujo nome começa com vogal",
    "Aves cujo nome começa com consoante",
    "Aves cujo nome tem mais de 8 letras",
    "Aves cujo nome tem menos de 5 letras",
    "Aves cujo nome tem exatamente duas sílabas",
    "Aves cujo nome termina com a letra A",
    "Aves cujo nome termina com a letra O",
    "Aves cujo nome contém a letra Z",
    "Aves cujo nome contém a letra C",
    "Aves cujo nome tem acento gráfico",
    "Aves cujo nome é uma palavra composta",
    "Aves que são (ou podem ser) predominantemente vermelhos",
    "Aves que são (ou podem ser) predominantemente verdes",
    "Aves que são (ou podem ser) predominantemente azuis",
    "Aves que são (ou podem ser) predominantemente amarelos",
    "Aves que são (ou podem ser) predominantemente brancos",
    "Aves que são (ou podem ser) predominantemente pretos",
    "Aves encontrados no Brasil",
    "Aves que vivem ou crescem na água",
    "Aves que vivem ou crescem em florestas",
    "Aves considerados grandes ou pesados",
    "Aves considerados pequenos ou leves",
    "Peixes cujo nome começa com vogal",
    "Peixes cujo nome começa com consoante",
    "Peixes cujo nome tem mais de 8 letras",
    "Peixes cujo nome tem menos de 5 letras",
    "Peixes cujo nome tem exatamente duas sílabas",
    "Peixes cujo nome termina com a letra A",
    "Peixes cujo nome termina com a letra O",
    "Peixes cujo nome contém a letra Z",
    "Peixes cujo nome contém a letra C",
    "Peixes cujo nome tem acento gráfico",
    "Peixes cujo nome é uma palavra composta",
    "Peixes que são (ou podem ser) predominantemente vermelhos",
    "Peixes que são (ou podem ser) predominantemente verdes",
    "Peixes que são (ou podem ser) predominantemente azuis",
    "Peixes que são (ou podem ser) predominantemente amarelos",
    "Peixes que são (ou podem ser) predominantemente brancos",
    "Peixes que são (ou podem ser) predominantemente pretos",
    "Peixes encontrados no Brasil",
    "Peixes que vivem ou crescem na água",
    "Peixes que vivem ou crescem em florestas",
    "Peixes considerados grandes ou pesados",
    "Peixes considerados pequenos ou leves",
    "Insetos cujo nome começa com vogal",
    "Insetos cujo nome começa com consoante",
    "Insetos cujo nome tem mais de 8 letras",
    "Insetos cujo nome tem menos de 5 letras",
    "Insetos cujo nome tem exatamente duas sílabas",
    "Insetos cujo nome termina com a letra A",
    "Insetos cujo nome termina com a letra O",
    "Insetos cujo nome contém a letra Z",
    "Insetos cujo nome contém a letra C",
    "Insetos cujo nome tem acento gráfico",
    "Insetos cujo nome é uma palavra composta",
    "Insetos que são (ou podem ser) predominantemente vermelhos",
    "Insetos que são (ou podem ser) predominantemente verdes",
    "Insetos que são (ou podem ser) predominantemente azuis",
    "Insetos que são (ou podem ser) predominantemente amarelos",
    "Insetos que são (ou podem ser) predominantemente brancos",
    "Insetos que são (ou podem ser) predominantemente pretos",
    "Insetos considerados grandes ou pesados",
    "Insetos considerados pequenos ou leves",
    "Répteis cujo nome começa com vogal",
    "Répteis cujo nome começa com consoante",
    "Répteis cujo nome tem mais de 8 letras",
    "Répteis cujo nome tem menos de 5 letras",
    "Répteis cujo nome tem exatamente duas sílabas",
    "Répteis cujo nome termina com a letra A",
    "Répteis cujo nome termina com a letra O",
    "Répteis cujo nome contém a letra Z",
    "Répteis cujo nome contém a letra C",
    "Répteis cujo nome tem acento gráfico",
    "Répteis cujo nome é uma palavra composta",
    "Répteis que são (ou podem ser) predominantemente vermelhos",
    "Répteis que são (ou podem ser) predominantemente verdes",
    "Répteis que são (ou podem ser) predominantemente azuis",
    "Répteis que são (ou podem ser) predominantemente amarelos",
    "Répteis que são (ou podem ser) predominantemente brancos",
    "Répteis que são (ou podem ser) predominantemente pretos",
    "Répteis considerados grandes ou pesados",
    "Répteis considerados pequenos ou leves",
    "Dinossauros cujo nome começa com vogal",
    "Dinossauros cujo nome começa com consoante",
    "Dinossauros cujo nome tem mais de 8 letras",
    "Dinossauros cujo nome tem menos de 5 letras",
    "Dinossauros cujo nome tem exatamente duas sílabas",
    "Dinossauros cujo nome termina com a letra A",
    "Dinossauros cujo nome termina com a letra O",
    "Dinossauros cujo nome contém a letra Z",
    "Dinossauros cujo nome contém a letra C",
    "Dinossauros cujo nome tem acento gráfico",
    "Dinossauros cujo nome é uma palavra composta",
    "Dinossauros considerados grandes ou pesados",
    "Dinossauros considerados pequenos ou leves",
    "Frutas cujo nome começa com vogal",
    "Frutas cujo nome começa com consoante",
    "Frutas cujo nome tem mais de 8 letras",
    "Frutas cujo nome tem menos de 5 letras",
    "Frutas cujo nome tem exatamente duas sílabas",
    "Frutas cujo nome termina com a letra A",
    "Frutas cujo nome termina com a letra O",
    "Frutas cujo nome contém a letra Z",
    "Frutas cujo nome contém a letra C",
    "Frutas cujo nome tem acento gráfico",
    "Frutas cujo nome é uma palavra composta",
    "Frutas que são (ou podem ser) predominantemente vermelhos",
    "Frutas que são (ou podem ser) predominantemente verdes",
    "Frutas que são (ou podem ser) predominantemente azuis",
    "Frutas que são (ou podem ser) predominantemente amarelos",
    "Frutas que são (ou podem ser) predominantemente brancos",
    "Frutas que são (ou podem ser) predominantemente pretos",
    "Frutas de origem ou fabricação brasileira",
    "Frutas de origem ou fabricação europeia",
    "Frutas de origem ou fabricação asiática",
    "Frutas de origem ou fabricação norte-americana",
    "Frutas considerados grandes ou pesados",
    "Frutas considerados pequenos ou leves",
    "Verduras e legumes cujo nome começa com vogal",
    "Verduras e legumes cujo nome começa com consoante",
    "Verduras e legumes cujo nome tem mais de 8 letras",
    "Verduras e legumes cujo nome tem menos de 5 letras",
    "Verduras e legumes cujo nome tem exatamente duas sílabas",
    "Verduras e legumes cujo nome termina com a letra A",
    "Verduras e legumes cujo nome termina com a letra O",
    "Verduras e legumes cujo nome contém a letra Z",
    "Verduras e legumes cujo nome contém a letra C",
    "Verduras e legumes cujo nome tem acento gráfico",
    "Verduras e legumes cujo nome é uma palavra composta",
    "Verduras e legumes que são (ou podem ser) predominantemente vermelhos",
    "Verduras e legumes que são (ou podem ser) predominantemente verdes",
    "Verduras e legumes que são (ou podem ser) predominantemente azuis",
    "Verduras e legumes que são (ou podem ser) predominantemente amarelos",
    "Verduras e legumes que são (ou podem ser) predominantemente brancos",
    "Verduras e legumes que são (ou podem ser) predominantemente pretos",
    "Flores cujo nome começa com vogal",
    "Flores cujo nome começa com consoante",
    "Flores cujo nome tem mais de 8 letras",
    "Flores cujo nome tem menos de 5 letras",
    "Flores cujo nome tem exatamente duas sílabas",
    "Flores cujo nome termina com a letra A",
    "Flores cujo nome termina com a letra O",
    "Flores cujo nome contém a letra Z",
    "Flores cujo nome contém a letra C",
    "Flores cujo nome tem acento gráfico",
    "Flores cujo nome é uma palavra composta",
    "Flores que são (ou podem ser) predominantemente vermelhos",
    "Flores que são (ou podem ser) predominantemente verdes",
    "Flores que são (ou podem ser) predominantemente azuis",
    "Flores que são (ou podem ser) predominantemente amarelos",
    "Flores que são (ou podem ser) predominantemente brancos",
    "Flores que são (ou podem ser) predominantemente pretos",
    "Árvores cujo nome começa com vogal",
    "Árvores cujo nome começa com consoante",
    "Árvores cujo nome tem mais de 8 letras",
    "Árvores cujo nome tem menos de 5 letras",
    "Árvores cujo nome tem exatamente duas sílabas",
    "Árvores cujo nome termina com a letra A",
    "Árvores cujo nome termina com a letra O",
    "Árvores cujo nome contém a letra Z",
    "Árvores cujo nome contém a letra C",
    "Árvores cujo nome tem acento gráfico",
    "Árvores cujo nome é uma palavra composta",
    "Árvores considerados grandes ou pesados",
    "Árvores considerados pequenos ou leves",
    "Países cujo nome começa com vogal",
    "Países cujo nome começa com consoante",
    "Países cujo nome tem mais de 8 letras",
    "Países cujo nome tem menos de 5 letras",
    "Países cujo nome tem exatamente duas sílabas",
    "Países cujo nome termina com a letra A",
    "Países cujo nome termina com a letra O",
    "Países cujo nome contém a letra Z",
    "Países cujo nome contém a letra C",
    "Países cujo nome tem acento gráfico",
    "Países cujo nome é uma palavra composta",
    "Cidades brasileiras cujo nome começa com vogal",
    "Cidades brasileiras cujo nome começa com consoante",
    "Cidades brasileiras cujo nome tem mais de 8 letras",
    "Cidades brasileiras cujo nome tem menos de 5 letras",
    "Cidades brasileiras cujo nome tem exatamente duas sílabas",
    "Cidades brasileiras cujo nome termina com a letra A",
    "Cidades brasileiras cujo nome termina com a letra O",
    "Cidades brasileiras cujo nome contém a letra Z",
    "Cidades brasileiras cujo nome contém a letra C",
    "Cidades brasileiras cujo nome tem acento gráfico",
    "Cidades brasileiras cujo nome é uma palavra composta",
    "Cidades brasileiras considerados grandes ou pesados",
    "Cidades brasileiras considerados pequenos ou leves",
    "Capitais do mundo cujo nome começa com vogal",
    "Capitais do mundo cujo nome começa com consoante",
    "Capitais do mundo cujo nome tem mais de 8 letras",
    "Capitais do mundo cujo nome tem menos de 5 letras",
    "Capitais do mundo cujo nome tem exatamente duas sílabas",
    "Capitais do mundo cujo nome termina com a letra A",
    "Capitais do mundo cujo nome termina com a letra O",
    "Capitais do mundo cujo nome contém a letra Z",
    "Capitais do mundo cujo nome contém a letra C",
    "Capitais do mundo cujo nome tem acento gráfico",
    "Capitais do mundo cujo nome é uma palavra composta",
    "Estados brasileiros cujo nome começa com vogal",
    "Estados brasileiros cujo nome começa com consoante",
    "Estados brasileiros cujo nome tem mais de 8 letras",
    "Estados brasileiros cujo nome tem menos de 5 letras",
    "Estados brasileiros cujo nome tem exatamente duas sílabas",
    "Estados brasileiros cujo nome termina com a letra A",
    "Estados brasileiros cujo nome termina com a letra O",
    "Estados brasileiros cujo nome contém a letra Z",
    "Estados brasileiros cujo nome contém a letra C",
    "Estados brasileiros cujo nome tem acento gráfico",
    "Estados brasileiros cujo nome é uma palavra composta",
    "Rios cujo nome começa com vogal",
    "Rios cujo nome começa com consoante",
    "Rios cujo nome tem mais de 8 letras",
    "Rios cujo nome tem menos de 5 letras",
    "Rios cujo nome tem exatamente duas sílabas",
    "Rios cujo nome termina com a letra A",
    "Rios cujo nome termina com a letra O",
    "Rios cujo nome contém a letra Z",
    "Rios cujo nome contém a letra C",
    "Rios cujo nome tem acento gráfico",
    "Rios cujo nome é uma palavra composta",
    "Rios considerados grandes ou pesados",
    "Rios considerados pequenos ou leves",
    "Praias brasileiras cujo nome começa com vogal",
    "Praias brasileiras cujo nome começa com consoante",
    "Praias brasileiras cujo nome tem mais de 8 letras",
    "Praias brasileiras cujo nome tem menos de 5 letras",
    "Praias brasileiras cujo nome tem exatamente duas sílabas",
    "Praias brasileiras cujo nome termina com a letra A",
    "Praias brasileiras cujo nome termina com a letra O",
    "Praias brasileiras cujo nome contém a letra Z",
    "Praias brasileiras cujo nome contém a letra C",
    "Praias brasileiras cujo nome tem acento gráfico",
    "Praias brasileiras cujo nome é uma palavra composta",
    "Praias brasileiras considerados grandes ou pesados",
    "Praias brasileiras considerados pequenos ou leves",
    "Pontos turísticos do Brasil cujo nome começa com vogal",
    "Pontos turísticos do Brasil cujo nome começa com consoante",
    "Pontos turísticos do Brasil cujo nome tem mais de 8 letras",
    "Pontos turísticos do Brasil cujo nome tem menos de 5 letras",
    "Pontos turísticos do Brasil cujo nome tem exatamente duas sílabas",
    "Pontos turísticos do Brasil cujo nome termina com a letra A",
    "Pontos turísticos do Brasil cujo nome termina com a letra O",
    "Pontos turísticos do Brasil cujo nome contém a letra Z",
    "Pontos turísticos do Brasil cujo nome contém a letra C",
    "Pontos turísticos do Brasil cujo nome tem acento gráfico",
    "Pontos turísticos do Brasil cujo nome é uma palavra composta",
    "Comidas cujo nome começa com vogal",
    "Comidas cujo nome começa com consoante",
    "Comidas cujo nome tem mais de 8 letras",
    "Comidas cujo nome tem menos de 5 letras",
    "Comidas cujo nome tem exatamente duas sílabas",
    "Comidas cujo nome termina com a letra A",
    "Comidas cujo nome termina com a letra O",
    "Comidas cujo nome contém a letra Z",
    "Comidas cujo nome contém a letra C",
    "Comidas cujo nome tem acento gráfico",
    "Comidas cujo nome é uma palavra composta",
    "Comidas que são (ou podem ser) predominantemente vermelhos",
    "Comidas que são (ou podem ser) predominantemente verdes",
    "Comidas que são (ou podem ser) predominantemente azuis",
    "Comidas que são (ou podem ser) predominantemente amarelos",
    "Comidas que são (ou podem ser) predominantemente brancos",
    "Comidas que são (ou podem ser) predominantemente pretos",
    "Comidas de origem ou fabricação brasileira",
    "Comidas de origem ou fabricação europeia",
    "Comidas de origem ou fabricação asiática",
    "Comidas de origem ou fabricação norte-americana",
    "Comidas típicas brasileiras cujo nome começa com vogal",
    "Comidas típicas brasileiras cujo nome começa com consoante",
    "Comidas típicas brasileiras cujo nome tem mais de 8 letras",
    "Comidas típicas brasileiras cujo nome tem menos de 5 letras",
    "Comidas típicas brasileiras cujo nome tem exatamente duas sílabas",
    "Comidas típicas brasileiras cujo nome termina com a letra A",
    "Comidas típicas brasileiras cujo nome termina com a letra O",
    "Comidas típicas brasileiras cujo nome contém a letra Z",
    "Comidas típicas brasileiras cujo nome contém a letra C",
    "Comidas típicas brasileiras cujo nome tem acento gráfico",
    "Comidas típicas brasileiras cujo nome é uma palavra composta",
    "Doces e sobremesas cujo nome começa com vogal",
    "Doces e sobremesas cujo nome começa com consoante",
    "Doces e sobremesas cujo nome tem mais de 8 letras",
    "Doces e sobremesas cujo nome tem menos de 5 letras",
    "Doces e sobremesas cujo nome tem exatamente duas sílabas",
    "Doces e sobremesas cujo nome termina com a letra A",
    "Doces e sobremesas cujo nome termina com a letra O",
    "Doces e sobremesas cujo nome contém a letra Z",
    "Doces e sobremesas cujo nome contém a letra C",
    "Doces e sobremesas cujo nome tem acento gráfico",
    "Doces e sobremesas cujo nome é uma palavra composta",
    "Doces e sobremesas que são (ou podem ser) predominantemente vermelhos",
    "Doces e sobremesas que são (ou podem ser) predominantemente verdes",
    "Doces e sobremesas que são (ou podem ser) predominantemente azuis",
    "Doces e sobremesas que são (ou podem ser) predominantemente amarelos",
    "Doces e sobremesas que são (ou podem ser) predominantemente brancos",
    "Doces e sobremesas que são (ou podem ser) predominantemente pretos",
    "Bebidas cujo nome começa com vogal",
    "Bebidas cujo nome começa com consoante",
    "Bebidas cujo nome tem mais de 8 letras",
    "Bebidas cujo nome tem menos de 5 letras",
    "Bebidas cujo nome tem exatamente duas sílabas",
    "Bebidas cujo nome termina com a letra A",
    "Bebidas cujo nome termina com a letra O",
    "Bebidas cujo nome contém a letra Z",
    "Bebidas cujo nome contém a letra C",
    "Bebidas cujo nome tem acento gráfico",
    "Bebidas cujo nome é uma palavra composta",
    "Bebidas que são (ou podem ser) predominantemente vermelhos",
    "Bebidas que são (ou podem ser) predominantemente verdes",
    "Bebidas que são (ou podem ser) predominantemente azuis",
    "Bebidas que são (ou podem ser) predominantemente amarelos",
    "Bebidas que são (ou podem ser) predominantemente brancos",
    "Bebidas que são (ou podem ser) predominantemente pretos",
    "Bebidas de origem ou fabricação brasileira",
    "Bebidas de origem ou fabricação europeia",
    "Bebidas de origem ou fabricação asiática",
    "Bebidas de origem ou fabricação norte-americana",
    "Frutos do mar cujo nome começa com vogal",
    "Frutos do mar cujo nome começa com consoante",
    "Frutos do mar cujo nome tem mais de 8 letras",
    "Frutos do mar cujo nome tem menos de 5 letras",
    "Frutos do mar cujo nome tem exatamente duas sílabas",
    "Frutos do mar cujo nome termina com a letra A",
    "Frutos do mar cujo nome termina com a letra O",
    "Frutos do mar cujo nome contém a letra Z",
    "Frutos do mar cujo nome contém a letra C",
    "Frutos do mar cujo nome tem acento gráfico",
    "Frutos do mar cujo nome é uma palavra composta",
    "Frutos do mar considerados grandes ou pesados",
    "Frutos do mar considerados pequenos ou leves",
    "Queijos cujo nome começa com vogal",
    "Queijos cujo nome começa com consoante",
    "Queijos cujo nome tem mais de 8 letras",
    "Queijos cujo nome tem menos de 5 letras",
    "Queijos cujo nome tem exatamente duas sílabas",
    "Queijos cujo nome termina com a letra A",
    "Queijos cujo nome termina com a letra O",
    "Queijos cujo nome contém a letra Z",
    "Queijos cujo nome contém a letra C",
    "Queijos cujo nome tem acento gráfico",
    "Queijos cujo nome é uma palavra composta",
    "Queijos de origem ou fabricação brasileira",
    "Queijos de origem ou fabricação europeia",
    "Queijos de origem ou fabricação asiática",
    "Queijos de origem ou fabricação norte-americana",
    "Massas e macarrões cujo nome começa com vogal",
    "Massas e macarrões cujo nome começa com consoante",
    "Massas e macarrões cujo nome tem mais de 8 letras",
    "Massas e macarrões cujo nome tem menos de 5 letras",
    "Massas e macarrões cujo nome tem exatamente duas sílabas",
    "Massas e macarrões cujo nome termina com a letra A",
    "Massas e macarrões cujo nome termina com a letra O",
    "Massas e macarrões cujo nome contém a letra Z",
    "Massas e macarrões cujo nome contém a letra C",
    "Massas e macarrões cujo nome tem acento gráfico",
    "Massas e macarrões cujo nome é uma palavra composta",
    "Lanches e fast food cujo nome começa com vogal",
    "Lanches e fast food cujo nome começa com consoante",
    "Lanches e fast food cujo nome tem mais de 8 letras",
    "Lanches e fast food cujo nome tem menos de 5 letras",
    "Lanches e fast food cujo nome tem exatamente duas sílabas",
    "Lanches e fast food cujo nome termina com a letra A",
    "Lanches e fast food cujo nome termina com a letra O",
    "Lanches e fast food cujo nome contém a letra Z",
    "Lanches e fast food cujo nome contém a letra C",
    "Lanches e fast food cujo nome tem acento gráfico",
    "Lanches e fast food cujo nome é uma palavra composta",
    "Objetos de cozinha cujo nome começa com vogal",
    "Objetos de cozinha cujo nome começa com consoante",
    "Objetos de cozinha cujo nome tem mais de 8 letras",
    "Objetos de cozinha cujo nome tem menos de 5 letras",
    "Objetos de cozinha cujo nome tem exatamente duas sílabas",
    "Objetos de cozinha cujo nome termina com a letra A",
    "Objetos de cozinha cujo nome termina com a letra O",
    "Objetos de cozinha cujo nome contém a letra Z",
    "Objetos de cozinha cujo nome contém a letra C",
    "Objetos de cozinha cujo nome tem acento gráfico",
    "Objetos de cozinha cujo nome é uma palavra composta",
    "Objetos de cozinha que são (ou podem ser) predominantemente vermelhos",
    "Objetos de cozinha que são (ou podem ser) predominantemente verdes",
    "Objetos de cozinha que são (ou podem ser) predominantemente azuis",
    "Objetos de cozinha que são (ou podem ser) predominantemente amarelos",
    "Objetos de cozinha que são (ou podem ser) predominantemente brancos",
    "Objetos de cozinha que são (ou podem ser) predominantemente pretos",
    "Objetos de cozinha considerados grandes ou pesados",
    "Objetos de cozinha considerados pequenos ou leves",
    "Objetos de cozinha que precisam de eletricidade ou bateria para funcionar",
    "Móveis cujo nome começa com vogal",
    "Móveis cujo nome começa com consoante",
    "Móveis cujo nome tem mais de 8 letras",
    "Móveis cujo nome tem menos de 5 letras",
    "Móveis cujo nome tem exatamente duas sílabas",
    "Móveis cujo nome termina com a letra A",
    "Móveis cujo nome termina com a letra O",
    "Móveis cujo nome contém a letra Z",
    "Móveis cujo nome contém a letra C",
    "Móveis cujo nome tem acento gráfico",
    "Móveis cujo nome é uma palavra composta",
    "Móveis que são (ou podem ser) predominantemente vermelhos",
    "Móveis que são (ou podem ser) predominantemente verdes",
    "Móveis que são (ou podem ser) predominantemente azuis",
    "Móveis que são (ou podem ser) predominantemente amarelos",
    "Móveis que são (ou podem ser) predominantemente brancos",
    "Móveis que são (ou podem ser) predominantemente pretos",
    "Móveis considerados grandes ou pesados",
    "Móveis considerados pequenos ou leves",
    "Eletrodomésticos cujo nome começa com vogal",
    "Eletrodomésticos cujo nome começa com consoante",
    "Eletrodomésticos cujo nome tem mais de 8 letras",
    "Eletrodomésticos cujo nome tem menos de 5 letras",
    "Eletrodomésticos cujo nome tem exatamente duas sílabas",
    "Eletrodomésticos cujo nome termina com a letra A",
    "Eletrodomésticos cujo nome termina com a letra O",
    "Eletrodomésticos cujo nome contém a letra Z",
    "Eletrodomésticos cujo nome contém a letra C",
    "Eletrodomésticos cujo nome tem acento gráfico",
    "Eletrodomésticos cujo nome é uma palavra composta",
    "Eletrodomésticos que são (ou podem ser) predominantemente vermelhos",
    "Eletrodomésticos que são (ou podem ser) predominantemente verdes",
    "Eletrodomésticos que são (ou podem ser) predominantemente azuis",
    "Eletrodomésticos que são (ou podem ser) predominantemente amarelos",
    "Eletrodomésticos que são (ou podem ser) predominantemente brancos",
    "Eletrodomésticos que são (ou podem ser) predominantemente pretos",
    "Eletrodomésticos considerados grandes ou pesados",
    "Eletrodomésticos considerados pequenos ou leves",
    "Eletrodomésticos que precisam de eletricidade ou bateria para funcionar",
    "Ferramentas cujo nome começa com vogal",
    "Ferramentas cujo nome começa com consoante",
    "Ferramentas cujo nome tem mais de 8 letras",
    "Ferramentas cujo nome tem menos de 5 letras",
    "Ferramentas cujo nome tem exatamente duas sílabas",
    "Ferramentas cujo nome termina com a letra A",
    "Ferramentas cujo nome termina com a letra O",
    "Ferramentas cujo nome contém a letra Z",
    "Ferramentas cujo nome contém a letra C",
    "Ferramentas cujo nome tem acento gráfico",
    "Ferramentas cujo nome é uma palavra composta",
    "Ferramentas que são (ou podem ser) predominantemente vermelhos",
    "Ferramentas que são (ou podem ser) predominantemente verdes",
    "Ferramentas que são (ou podem ser) predominantemente azuis",
    "Ferramentas que são (ou podem ser) predominantemente amarelos",
    "Ferramentas que são (ou podem ser) predominantemente brancos",
    "Ferramentas que são (ou podem ser) predominantemente pretos",
    "Ferramentas considerados grandes ou pesados",
    "Ferramentas considerados pequenos ou leves",
    "Ferramentas que precisam de eletricidade ou bateria para funcionar",
    "Brinquedos cujo nome começa com vogal",
    "Brinquedos cujo nome começa com consoante",
    "Brinquedos cujo nome tem mais de 8 letras",
    "Brinquedos cujo nome tem menos de 5 letras",
    "Brinquedos cujo nome tem exatamente duas sílabas",
    "Brinquedos cujo nome termina com a letra A",
    "Brinquedos cujo nome termina com a letra O",
    "Brinquedos cujo nome contém a letra Z",
    "Brinquedos cujo nome contém a letra C",
    "Brinquedos cujo nome tem acento gráfico",
    "Brinquedos cujo nome é uma palavra composta",
    "Brinquedos que são (ou podem ser) predominantemente vermelhos",
    "Brinquedos que são (ou podem ser) predominantemente verdes",
    "Brinquedos que são (ou podem ser) predominantemente azuis",
    "Brinquedos que são (ou podem ser) predominantemente amarelos",
    "Brinquedos que são (ou podem ser) predominantemente brancos",
    "Brinquedos que são (ou podem ser) predominantemente pretos",
    "Brinquedos considerados grandes ou pesados",
    "Brinquedos considerados pequenos ou leves",
    "Brinquedos considerados clássicos (criados há mais de 20 anos)",
    "Brinquedos lançados ou populares nos últimos 10 anos",
    "Instrumentos musicais cujo nome começa com vogal",
    "Instrumentos musicais cujo nome começa com consoante",
    "Instrumentos musicais cujo nome tem mais de 8 letras",
    "Instrumentos musicais cujo nome tem menos de 5 letras",
    "Instrumentos musicais cujo nome tem exatamente duas sílabas",
    "Instrumentos musicais cujo nome termina com a letra A",
    "Instrumentos musicais cujo nome termina com a letra O",
    "Instrumentos musicais cujo nome contém a letra Z",
    "Instrumentos musicais cujo nome contém a letra C",
    "Instrumentos musicais cujo nome tem acento gráfico",
    "Instrumentos musicais cujo nome é uma palavra composta",
    "Instrumentos musicais que são (ou podem ser) predominantemente vermelhos",
    "Instrumentos musicais que são (ou podem ser) predominantemente verdes",
    "Instrumentos musicais que são (ou podem ser) predominantemente azuis",
    "Instrumentos musicais que são (ou podem ser) predominantemente amarelos",
    "Instrumentos musicais que são (ou podem ser) predominantemente brancos",
    "Instrumentos musicais que são (ou podem ser) predominantemente pretos",
    "Instrumentos musicais considerados grandes ou pesados",
    "Instrumentos musicais considerados pequenos ou leves",
    "Instrumentos musicais que precisam de eletricidade ou bateria para funcionar",
    "Roupas cujo nome começa com vogal",
    "Roupas cujo nome começa com consoante",
    "Roupas cujo nome tem mais de 8 letras",
    "Roupas cujo nome tem menos de 5 letras",
    "Roupas cujo nome tem exatamente duas sílabas",
    "Roupas cujo nome termina com a letra A",
    "Roupas cujo nome termina com a letra O",
    "Roupas cujo nome contém a letra Z",
    "Roupas cujo nome contém a letra C",
    "Roupas cujo nome tem acento gráfico",
    "Roupas cujo nome é uma palavra composta",
    "Roupas que são (ou podem ser) predominantemente vermelhos",
    "Roupas que são (ou podem ser) predominantemente verdes",
    "Roupas que são (ou podem ser) predominantemente azuis",
    "Roupas que são (ou podem ser) predominantemente amarelos",
    "Roupas que são (ou podem ser) predominantemente brancos",
    "Roupas que são (ou podem ser) predominantemente pretos",
    "Calçados cujo nome começa com vogal",
    "Calçados cujo nome começa com consoante",
    "Calçados cujo nome tem mais de 8 letras",
    "Calçados cujo nome tem menos de 5 letras",
    "Calçados cujo nome tem exatamente duas sílabas",
    "Calçados cujo nome termina com a letra A",
    "Calçados cujo nome termina com a letra O",
    "Calçados cujo nome contém a letra Z",
    "Calçados cujo nome contém a letra C",
    "Calçados cujo nome tem acento gráfico",
    "Calçados cujo nome é uma palavra composta",
    "Calçados que são (ou podem ser) predominantemente vermelhos",
    "Calçados que são (ou podem ser) predominantemente verdes",
    "Calçados que são (ou podem ser) predominantemente azuis",
    "Calçados que são (ou podem ser) predominantemente amarelos",
    "Calçados que são (ou podem ser) predominantemente brancos",
    "Calçados que são (ou podem ser) predominantemente pretos",
    "Acessórios (bolsas, relógios, óculos etc.) cujo nome começa com vogal",
    "Acessórios (bolsas, relógios, óculos etc.) cujo nome começa com consoante",
    "Acessórios (bolsas, relógios, óculos etc.) cujo nome tem mais de 8 letras",
    "Acessórios (bolsas, relógios, óculos etc.) cujo nome tem menos de 5 letras",
    "Acessórios (bolsas, relógios, óculos etc.) cujo nome tem exatamente duas sílabas",
    "Acessórios (bolsas, relógios, óculos etc.) cujo nome termina com a letra A",
    "Acessórios (bolsas, relógios, óculos etc.) cujo nome termina com a letra O",
    "Acessórios (bolsas, relógios, óculos etc.) cujo nome contém a letra Z",
    "Acessórios (bolsas, relógios, óculos etc.) cujo nome contém a letra C",
    "Acessórios (bolsas, relógios, óculos etc.) cujo nome tem acento gráfico",
    "Acessórios (bolsas, relógios, óculos etc.) cujo nome é uma palavra composta",
    "Acessórios (bolsas, relógios, óculos etc.) que são (ou podem ser) predominantemente vermelhos",
    "Acessórios (bolsas, relógios, óculos etc.) que são (ou podem ser) predominantemente verdes",
    "Acessórios (bolsas, relógios, óculos etc.) que são (ou podem ser) predominantemente azuis",
    "Acessórios (bolsas, relógios, óculos etc.) que são (ou podem ser) predominantemente amarelos",
    "Acessórios (bolsas, relógios, óculos etc.) que são (ou podem ser) predominantemente brancos",
    "Acessórios (bolsas, relógios, óculos etc.) que são (ou podem ser) predominantemente pretos",
    "Objetos escolares cujo nome começa com vogal",
    "Objetos escolares cujo nome começa com consoante",
    "Objetos escolares cujo nome tem mais de 8 letras",
    "Objetos escolares cujo nome tem menos de 5 letras",
    "Objetos escolares cujo nome tem exatamente duas sílabas",
    "Objetos escolares cujo nome termina com a letra A",
    "Objetos escolares cujo nome termina com a letra O",
    "Objetos escolares cujo nome contém a letra Z",
    "Objetos escolares cujo nome contém a letra C",
    "Objetos escolares cujo nome tem acento gráfico",
    "Objetos escolares cujo nome é uma palavra composta",
    "Objetos escolares que são (ou podem ser) predominantemente vermelhos",
    "Objetos escolares que são (ou podem ser) predominantemente verdes",
    "Objetos escolares que são (ou podem ser) predominantemente azuis",
    "Objetos escolares que são (ou podem ser) predominantemente amarelos",
    "Objetos escolares que são (ou podem ser) predominantemente brancos",
    "Objetos escolares que são (ou podem ser) predominantemente pretos",
    "Aparelhos eletrônicos cujo nome começa com vogal",
    "Aparelhos eletrônicos cujo nome começa com consoante",
    "Aparelhos eletrônicos cujo nome tem mais de 8 letras",
    "Aparelhos eletrônicos cujo nome tem menos de 5 letras",
    "Aparelhos eletrônicos cujo nome tem exatamente duas sílabas",
    "Aparelhos eletrônicos cujo nome termina com a letra A",
    "Aparelhos eletrônicos cujo nome termina com a letra O",
    "Aparelhos eletrônicos cujo nome contém a letra Z",
    "Aparelhos eletrônicos cujo nome contém a letra C",
    "Aparelhos eletrônicos cujo nome tem acento gráfico",
    "Aparelhos eletrônicos cujo nome é uma palavra composta",
    "Aparelhos eletrônicos que são (ou podem ser) predominantemente vermelhos",
    "Aparelhos eletrônicos que são (ou podem ser) predominantemente verdes",
    "Aparelhos eletrônicos que são (ou podem ser) predominantemente azuis",
    "Aparelhos eletrônicos que são (ou podem ser) predominantemente amarelos",
    "Aparelhos eletrônicos que são (ou podem ser) predominantemente brancos",
    "Aparelhos eletrônicos que são (ou podem ser) predominantemente pretos",
    "Aparelhos eletrônicos considerados grandes ou pesados",
    "Aparelhos eletrônicos considerados pequenos ou leves",
    "Aparelhos eletrônicos que precisam de eletricidade ou bateria para funcionar",
    "Aparelhos eletrônicos considerados clássicos (criados há mais de 20 anos)",
    "Aparelhos eletrônicos lançados ou populares nos últimos 10 anos",
    "Profissões cujo nome começa com vogal",
    "Profissões cujo nome começa com consoante",
    "Profissões cujo nome tem mais de 8 letras",
    "Profissões cujo nome tem menos de 5 letras",
    "Profissões cujo nome tem exatamente duas sílabas",
    "Profissões cujo nome termina com a letra A",
    "Profissões cujo nome termina com a letra O",
    "Profissões cujo nome contém a letra Z",
    "Profissões cujo nome contém a letra C",
    "Profissões cujo nome tem acento gráfico",
    "Profissões cujo nome é uma palavra composta",
    "Profissões da saúde cujo nome começa com vogal",
    "Profissões da saúde cujo nome começa com consoante",
    "Profissões da saúde cujo nome tem mais de 8 letras",
    "Profissões da saúde cujo nome tem menos de 5 letras",
    "Profissões da saúde cujo nome tem exatamente duas sílabas",
    "Profissões da saúde cujo nome termina com a letra A",
    "Profissões da saúde cujo nome termina com a letra O",
    "Profissões da saúde cujo nome contém a letra Z",
    "Profissões da saúde cujo nome contém a letra C",
    "Profissões da saúde cujo nome tem acento gráfico",
    "Profissões da saúde cujo nome é uma palavra composta",
    "Profissões esportivas cujo nome começa com vogal",
    "Profissões esportivas cujo nome começa com consoante",
    "Profissões esportivas cujo nome tem mais de 8 letras",
    "Profissões esportivas cujo nome tem menos de 5 letras",
    "Profissões esportivas cujo nome tem exatamente duas sílabas",
    "Profissões esportivas cujo nome termina com a letra A",
    "Profissões esportivas cujo nome termina com a letra O",
    "Profissões esportivas cujo nome contém a letra Z",
    "Profissões esportivas cujo nome contém a letra C",
    "Profissões esportivas cujo nome tem acento gráfico",
    "Profissões esportivas cujo nome é uma palavra composta",
    "Profissões artísticas cujo nome começa com vogal",
    "Profissões artísticas cujo nome começa com consoante",
    "Profissões artísticas cujo nome tem mais de 8 letras",
    "Profissões artísticas cujo nome tem menos de 5 letras",
    "Profissões artísticas cujo nome tem exatamente duas sílabas",
    "Profissões artísticas cujo nome termina com a letra A",
    "Profissões artísticas cujo nome termina com a letra O",
    "Profissões artísticas cujo nome contém a letra Z",
    "Profissões artísticas cujo nome contém a letra C",
    "Profissões artísticas cujo nome tem acento gráfico",
    "Profissões artísticas cujo nome é uma palavra composta",
    "Filmes cujo nome começa com vogal",
    "Filmes cujo nome começa com consoante",
    "Filmes cujo nome tem mais de 8 letras",
    "Filmes cujo nome tem menos de 5 letras",
    "Filmes cujo nome tem exatamente duas sílabas",
    "Filmes cujo nome termina com a letra A",
    "Filmes cujo nome termina com a letra O",
    "Filmes cujo nome contém a letra Z",
    "Filmes cujo nome contém a letra C",
    "Filmes cujo nome tem acento gráfico",
    "Filmes cujo nome é uma palavra composta",
    "Filmes considerados clássicos (criados há mais de 20 anos)",
    "Filmes lançados ou populares nos últimos 10 anos",
    "Filmes de animação cujo nome começa com vogal",
    "Filmes de animação cujo nome começa com consoante",
    "Filmes de animação cujo nome tem mais de 8 letras",
    "Filmes de animação cujo nome tem menos de 5 letras",
    "Filmes de animação cujo nome tem exatamente duas sílabas",
    "Filmes de animação cujo nome termina com a letra A",
    "Filmes de animação cujo nome termina com a letra O",
    "Filmes de animação cujo nome contém a letra Z",
    "Filmes de animação cujo nome contém a letra C",
    "Filmes de animação cujo nome tem acento gráfico",
    "Filmes de animação cujo nome é uma palavra composta",
    "Filmes de animação considerados clássicos (criados há mais de 20 anos)",
    "Filmes de animação lançados ou populares nos últimos 10 anos",
    "Filmes de terror cujo nome começa com vogal",
    "Filmes de terror cujo nome começa com consoante",
    "Filmes de terror cujo nome tem mais de 8 letras",
    "Filmes de terror cujo nome tem menos de 5 letras",
    "Filmes de terror cujo nome tem exatamente duas sílabas",
    "Filmes de terror cujo nome termina com a letra A",
    "Filmes de terror cujo nome termina com a letra O",
    "Filmes de terror cujo nome contém a letra Z",
    "Filmes de terror cujo nome contém a letra C",
    "Filmes de terror cujo nome tem acento gráfico",
    "Filmes de terror cujo nome é uma palavra composta",
    "Filmes de terror considerados clássicos (criados há mais de 20 anos)",
    "Filmes de terror lançados ou populares nos últimos 10 anos",
    "Séries de TV cujo nome começa com vogal",
    "Séries de TV cujo nome começa com consoante",
    "Séries de TV cujo nome tem mais de 8 letras",
    "Séries de TV cujo nome tem menos de 5 letras",
    "Séries de TV cujo nome tem exatamente duas sílabas",
    "Séries de TV cujo nome termina com a letra A",
    "Séries de TV cujo nome termina com a letra O",
    "Séries de TV cujo nome contém a letra Z",
    "Séries de TV cujo nome contém a letra C",
    "Séries de TV cujo nome tem acento gráfico",
    "Séries de TV cujo nome é uma palavra composta",
    "Séries de TV considerados clássicos (criados há mais de 20 anos)",
    "Séries de TV lançados ou populares nos últimos 10 anos",
    "Desenhos animados cujo nome começa com vogal",
    "Desenhos animados cujo nome começa com consoante",
    "Desenhos animados cujo nome tem mais de 8 letras",
    "Desenhos animados cujo nome tem menos de 5 letras",
    "Desenhos animados cujo nome tem exatamente duas sílabas",
    "Desenhos animados cujo nome termina com a letra A",
    "Desenhos animados cujo nome termina com a letra O",
    "Desenhos animados cujo nome contém a letra Z",
    "Desenhos animados cujo nome contém a letra C",
    "Desenhos animados cujo nome tem acento gráfico",
    "Desenhos animados cujo nome é uma palavra composta",
    "Desenhos animados considerados clássicos (criados há mais de 20 anos)",
    "Desenhos animados lançados ou populares nos últimos 10 anos",
    "Super-heróis cujo nome começa com vogal",
    "Super-heróis cujo nome começa com consoante",
    "Super-heróis cujo nome tem mais de 8 letras",
    "Super-heróis cujo nome tem menos de 5 letras",
    "Super-heróis cujo nome tem exatamente duas sílabas",
    "Super-heróis cujo nome termina com a letra A",
    "Super-heróis cujo nome termina com a letra O",
    "Super-heróis cujo nome contém a letra Z",
    "Super-heróis cujo nome contém a letra C",
    "Super-heróis cujo nome tem acento gráfico",
    "Super-heróis cujo nome é uma palavra composta",
    "Super-heróis que são (ou podem ser) predominantemente vermelhos",
    "Super-heróis que são (ou podem ser) predominantemente verdes",
    "Super-heróis que são (ou podem ser) predominantemente azuis",
    "Super-heróis que são (ou podem ser) predominantemente amarelos",
    "Super-heróis que são (ou podem ser) predominantemente brancos",
    "Super-heróis que são (ou podem ser) predominantemente pretos",
    "Vilões de filmes e séries cujo nome começa com vogal",
    "Vilões de filmes e séries cujo nome começa com consoante",
    "Vilões de filmes e séries cujo nome tem mais de 8 letras",
    "Vilões de filmes e séries cujo nome tem menos de 5 letras",
    "Vilões de filmes e séries cujo nome tem exatamente duas sílabas",
    "Vilões de filmes e séries cujo nome termina com a letra A",
    "Vilões de filmes e séries cujo nome termina com a letra O",
    "Vilões de filmes e séries cujo nome contém a letra Z",
    "Vilões de filmes e séries cujo nome contém a letra C",
    "Vilões de filmes e séries cujo nome tem acento gráfico",
    "Vilões de filmes e séries cujo nome é uma palavra composta",
    "Video games cujo nome começa com vogal",
    "Video games cujo nome começa com consoante",
    "Video games cujo nome tem mais de 8 letras",
    "Video games cujo nome tem menos de 5 letras",
    "Video games cujo nome tem exatamente duas sílabas",
    "Video games cujo nome termina com a letra A",
    "Video games cujo nome termina com a letra O",
    "Video games cujo nome contém a letra Z",
    "Video games cujo nome contém a letra C",
    "Video games cujo nome tem acento gráfico",
    "Video games cujo nome é uma palavra composta",
    "Video games considerados clássicos (criados há mais de 20 anos)",
    "Video games lançados ou populares nos últimos 10 anos",
    "Personagens de jogos cujo nome começa com vogal",
    "Personagens de jogos cujo nome começa com consoante",
    "Personagens de jogos cujo nome tem mais de 8 letras",
    "Personagens de jogos cujo nome tem menos de 5 letras",
    "Personagens de jogos cujo nome tem exatamente duas sílabas",
    "Personagens de jogos cujo nome termina com a letra A",
    "Personagens de jogos cujo nome termina com a letra O",
    "Personagens de jogos cujo nome contém a letra Z",
    "Personagens de jogos cujo nome contém a letra C",
    "Personagens de jogos cujo nome tem acento gráfico",
    "Personagens de jogos cujo nome é uma palavra composta",
    "Livros infantis cujo nome começa com vogal",
    "Livros infantis cujo nome começa com consoante",
    "Livros infantis cujo nome tem mais de 8 letras",
    "Livros infantis cujo nome tem menos de 5 letras",
    "Livros infantis cujo nome tem exatamente duas sílabas",
    "Livros infantis cujo nome termina com a letra A",
    "Livros infantis cujo nome termina com a letra O",
    "Livros infantis cujo nome contém a letra Z",
    "Livros infantis cujo nome contém a letra C",
    "Livros infantis cujo nome tem acento gráfico",
    "Livros infantis cujo nome é uma palavra composta",
    "Livros infantis considerados clássicos (criados há mais de 20 anos)",
    "Livros infantis lançados ou populares nos últimos 10 anos",
    "Quadrinhos e mangás cujo nome começa com vogal",
    "Quadrinhos e mangás cujo nome começa com consoante",
    "Quadrinhos e mangás cujo nome tem mais de 8 letras",
    "Quadrinhos e mangás cujo nome tem menos de 5 letras",
    "Quadrinhos e mangás cujo nome tem exatamente duas sílabas",
    "Quadrinhos e mangás cujo nome termina com a letra A",
    "Quadrinhos e mangás cujo nome termina com a letra O",
    "Quadrinhos e mangás cujo nome contém a letra Z",
    "Quadrinhos e mangás cujo nome contém a letra C",
    "Quadrinhos e mangás cujo nome tem acento gráfico",
    "Quadrinhos e mangás cujo nome é uma palavra composta",
    "Quadrinhos e mangás considerados clássicos (criados há mais de 20 anos)",
    "Quadrinhos e mangás lançados ou populares nos últimos 10 anos",
    "Bandas cujo nome começa com vogal",
    "Bandas cujo nome começa com consoante",
    "Bandas cujo nome tem mais de 8 letras",
    "Bandas cujo nome tem menos de 5 letras",
    "Bandas cujo nome tem exatamente duas sílabas",
    "Bandas cujo nome termina com a letra A",
    "Bandas cujo nome termina com a letra O",
    "Bandas cujo nome contém a letra Z",
    "Bandas cujo nome contém a letra C",
    "Bandas cujo nome tem acento gráfico",
    "Bandas cujo nome é uma palavra composta",
    "Bandas de origem ou fabricação brasileira",
    "Bandas de origem ou fabricação europeia",
    "Bandas de origem ou fabricação asiática",
    "Bandas de origem ou fabricação norte-americana",
    "Bandas considerados clássicos (criados há mais de 20 anos)",
    "Bandas lançados ou populares nos últimos 10 anos",
    "Cantores brasileiros cujo nome começa com vogal",
    "Cantores brasileiros cujo nome começa com consoante",
    "Cantores brasileiros cujo nome tem mais de 8 letras",
    "Cantores brasileiros cujo nome tem menos de 5 letras",
    "Cantores brasileiros cujo nome tem exatamente duas sílabas",
    "Cantores brasileiros cujo nome termina com a letra A",
    "Cantores brasileiros cujo nome termina com a letra O",
    "Cantores brasileiros cujo nome contém a letra Z",
    "Cantores brasileiros cujo nome contém a letra C",
    "Cantores brasileiros cujo nome tem acento gráfico",
    "Cantores brasileiros cujo nome é uma palavra composta",
    "Cantores brasileiros considerados clássicos (criados há mais de 20 anos)",
    "Cantores brasileiros lançados ou populares nos últimos 10 anos",
    "Cantores internacionais cujo nome começa com vogal",
    "Cantores internacionais cujo nome começa com consoante",
    "Cantores internacionais cujo nome tem mais de 8 letras",
    "Cantores internacionais cujo nome tem menos de 5 letras",
    "Cantores internacionais cujo nome tem exatamente duas sílabas",
    "Cantores internacionais cujo nome termina com a letra A",
    "Cantores internacionais cujo nome termina com a letra O",
    "Cantores internacionais cujo nome contém a letra Z",
    "Cantores internacionais cujo nome contém a letra C",
    "Cantores internacionais cujo nome tem acento gráfico",
    "Cantores internacionais cujo nome é uma palavra composta",
    "Cantores internacionais considerados clássicos (criados há mais de 20 anos)",
    "Cantores internacionais lançados ou populares nos últimos 10 anos",
    "Atores brasileiros cujo nome começa com vogal",
    "Atores brasileiros cujo nome começa com consoante",
    "Atores brasileiros cujo nome tem mais de 8 letras",
    "Atores brasileiros cujo nome tem menos de 5 letras",
    "Atores brasileiros cujo nome tem exatamente duas sílabas",
    "Atores brasileiros cujo nome termina com a letra A",
    "Atores brasileiros cujo nome termina com a letra O",
    "Atores brasileiros cujo nome contém a letra Z",
    "Atores brasileiros cujo nome contém a letra C",
    "Atores brasileiros cujo nome tem acento gráfico",
    "Atores brasileiros cujo nome é uma palavra composta",
    "Atores internacionais cujo nome começa com vogal",
    "Atores internacionais cujo nome começa com consoante",
    "Atores internacionais cujo nome tem mais de 8 letras",
    "Atores internacionais cujo nome tem menos de 5 letras",
    "Atores internacionais cujo nome tem exatamente duas sílabas",
    "Atores internacionais cujo nome termina com a letra A",
    "Atores internacionais cujo nome termina com a letra O",
    "Atores internacionais cujo nome contém a letra Z",
    "Atores internacionais cujo nome contém a letra C",
    "Atores internacionais cujo nome tem acento gráfico",
    "Atores internacionais cujo nome é uma palavra composta",
    "Esportes cujo nome começa com vogal",
    "Esportes cujo nome começa com consoante",
    "Esportes cujo nome tem mais de 8 letras",
    "Esportes cujo nome tem menos de 5 letras",
    "Esportes cujo nome tem exatamente duas sílabas",
    "Esportes cujo nome termina com a letra A",
    "Esportes cujo nome termina com a letra O",
    "Esportes cujo nome contém a letra Z",
    "Esportes cujo nome contém a letra C",
    "Esportes cujo nome tem acento gráfico",
    "Esportes cujo nome é uma palavra composta",
    "Esportes olímpicos cujo nome começa com vogal",
    "Esportes olímpicos cujo nome começa com consoante",
    "Esportes olímpicos cujo nome tem mais de 8 letras",
    "Esportes olímpicos cujo nome tem menos de 5 letras",
    "Esportes olímpicos cujo nome tem exatamente duas sílabas",
    "Esportes olímpicos cujo nome termina com a letra A",
    "Esportes olímpicos cujo nome termina com a letra O",
    "Esportes olímpicos cujo nome contém a letra Z",
    "Esportes olímpicos cujo nome contém a letra C",
    "Esportes olímpicos cujo nome tem acento gráfico",
    "Esportes olímpicos cujo nome é uma palavra composta",
    "Times de futebol brasileiros cujo nome começa com vogal",
    "Times de futebol brasileiros cujo nome começa com consoante",
    "Times de futebol brasileiros cujo nome tem mais de 8 letras",
    "Times de futebol brasileiros cujo nome tem menos de 5 letras",
    "Times de futebol brasileiros cujo nome tem exatamente duas sílabas",
    "Times de futebol brasileiros cujo nome termina com a letra A",
    "Times de futebol brasileiros cujo nome termina com a letra O",
    "Times de futebol brasileiros cujo nome contém a letra Z",
    "Times de futebol brasileiros cujo nome contém a letra C",
    "Times de futebol brasileiros cujo nome tem acento gráfico",
    "Times de futebol brasileiros cujo nome é uma palavra composta",
    "Times de futebol brasileiros que são (ou podem ser) predominantemente vermelhos",
    "Times de futebol brasileiros que são (ou podem ser) predominantemente verdes",
    "Times de futebol brasileiros que são (ou podem ser) predominantemente azuis",
    "Times de futebol brasileiros que são (ou podem ser) predominantemente amarelos",
    "Times de futebol brasileiros que são (ou podem ser) predominantemente brancos",
    "Times de futebol brasileiros que são (ou podem ser) predominantemente pretos",
    "Seleções de futebol cujo nome começa com vogal",
    "Seleções de futebol cujo nome começa com consoante",
    "Seleções de futebol cujo nome tem mais de 8 letras",
    "Seleções de futebol cujo nome tem menos de 5 letras",
    "Seleções de futebol cujo nome tem exatamente duas sílabas",
    "Seleções de futebol cujo nome termina com a letra A",
    "Seleções de futebol cujo nome termina com a letra O",
    "Seleções de futebol cujo nome contém a letra Z",
    "Seleções de futebol cujo nome contém a letra C",
    "Seleções de futebol cujo nome tem acento gráfico",
    "Seleções de futebol cujo nome é uma palavra composta",
    "Seleções de futebol que são (ou podem ser) predominantemente vermelhos",
    "Seleções de futebol que são (ou podem ser) predominantemente verdes",
    "Seleções de futebol que são (ou podem ser) predominantemente azuis",
    "Seleções de futebol que são (ou podem ser) predominantemente amarelos",
    "Seleções de futebol que são (ou podem ser) predominantemente brancos",
    "Seleções de futebol que são (ou podem ser) predominantemente pretos",
    "Modalidades de luta cujo nome começa com vogal",
    "Modalidades de luta cujo nome começa com consoante",
    "Modalidades de luta cujo nome tem mais de 8 letras",
    "Modalidades de luta cujo nome tem menos de 5 letras",
    "Modalidades de luta cujo nome tem exatamente duas sílabas",
    "Modalidades de luta cujo nome termina com a letra A",
    "Modalidades de luta cujo nome termina com a letra O",
    "Modalidades de luta cujo nome contém a letra Z",
    "Modalidades de luta cujo nome contém a letra C",
    "Modalidades de luta cujo nome tem acento gráfico",
    "Modalidades de luta cujo nome é uma palavra composta",
    "Esportes com bola cujo nome começa com vogal",
    "Esportes com bola cujo nome começa com consoante",
    "Esportes com bola cujo nome tem mais de 8 letras",
    "Esportes com bola cujo nome tem menos de 5 letras",
    "Esportes com bola cujo nome tem exatamente duas sílabas",
    "Esportes com bola cujo nome termina com a letra A",
    "Esportes com bola cujo nome termina com a letra O",
    "Esportes com bola cujo nome contém a letra Z",
    "Esportes com bola cujo nome contém a letra C",
    "Esportes com bola cujo nome tem acento gráfico",
    "Esportes com bola cujo nome é uma palavra composta",
    "Esportes aquáticos cujo nome começa com vogal",
    "Esportes aquáticos cujo nome começa com consoante",
    "Esportes aquáticos cujo nome tem mais de 8 letras",
    "Esportes aquáticos cujo nome tem menos de 5 letras",
    "Esportes aquáticos cujo nome tem exatamente duas sílabas",
    "Esportes aquáticos cujo nome termina com a letra A",
    "Esportes aquáticos cujo nome termina com a letra O",
    "Esportes aquáticos cujo nome contém a letra Z",
    "Esportes aquáticos cujo nome contém a letra C",
    "Esportes aquáticos cujo nome tem acento gráfico",
    "Esportes aquáticos cujo nome é uma palavra composta",
    "Esportes de inverno cujo nome começa com vogal",
    "Esportes de inverno cujo nome começa com consoante",
    "Esportes de inverno cujo nome tem mais de 8 letras",
    "Esportes de inverno cujo nome tem menos de 5 letras",
    "Esportes de inverno cujo nome tem exatamente duas sílabas",
    "Esportes de inverno cujo nome termina com a letra A",
    "Esportes de inverno cujo nome termina com a letra O",
    "Esportes de inverno cujo nome contém a letra Z",
    "Esportes de inverno cujo nome contém a letra C",
    "Esportes de inverno cujo nome tem acento gráfico",
    "Esportes de inverno cujo nome é uma palavra composta",
    "Meios de transporte cujo nome começa com vogal",
    "Meios de transporte cujo nome começa com consoante",
    "Meios de transporte cujo nome tem mais de 8 letras",
    "Meios de transporte cujo nome tem menos de 5 letras",
    "Meios de transporte cujo nome tem exatamente duas sílabas",
    "Meios de transporte cujo nome termina com a letra A",
    "Meios de transporte cujo nome termina com a letra O",
    "Meios de transporte cujo nome contém a letra Z",
    "Meios de transporte cujo nome contém a letra C",
    "Meios de transporte cujo nome tem acento gráfico",
    "Meios de transporte cujo nome é uma palavra composta",
    "Meios de transporte que são (ou podem ser) predominantemente vermelhos",
    "Meios de transporte que são (ou podem ser) predominantemente verdes",
    "Meios de transporte que são (ou podem ser) predominantemente azuis",
    "Meios de transporte que são (ou podem ser) predominantemente amarelos",
    "Meios de transporte que são (ou podem ser) predominantemente brancos",
    "Meios de transporte que são (ou podem ser) predominantemente pretos",
    "Meios de transporte considerados grandes ou pesados",
    "Meios de transporte considerados pequenos ou leves",
    "Meios de transporte que precisam de eletricidade ou bateria para funcionar",
    "Marcas de carro cujo nome começa com vogal",
    "Marcas de carro cujo nome começa com consoante",
    "Marcas de carro cujo nome tem mais de 8 letras",
    "Marcas de carro cujo nome tem menos de 5 letras",
    "Marcas de carro cujo nome termina com a letra A",
    "Marcas de carro cujo nome termina com a letra O",
    "Marcas de celular cujo nome começa com vogal",
    "Marcas de celular cujo nome começa com consoante",
    "Marcas de celular cujo nome tem mais de 8 letras",
    "Marcas de celular cujo nome tem menos de 5 letras",
    "Aplicativos de celular cujo nome começa com vogal",
    "Aplicativos de celular cujo nome começa com consoante",
    "Aplicativos de celular cujo nome tem mais de 8 letras",
    "Aplicativos de celular cujo nome tem menos de 5 letras",
    "Aplicativos de celular cujo nome tem exatamente duas sílabas",
    "Aplicativos de celular cujo nome termina com a letra A",
    "Aplicativos de celular cujo nome termina com a letra O",
    "Aplicativos de celular cujo nome contém a letra Z",
    "Aplicativos de celular cujo nome contém a letra C",
    "Aplicativos de celular cujo nome tem acento gráfico",
    "Aplicativos de celular cujo nome é uma palavra composta",
    "Aplicativos de celular considerados clássicos (criados há mais de 20 anos)",
    "Aplicativos de celular lançados ou populares nos últimos 10 anos",
    "Redes sociais cujo nome começa com vogal",
    "Redes sociais cujo nome começa com consoante",
    "Redes sociais cujo nome tem mais de 8 letras",
    "Redes sociais cujo nome tem menos de 5 letras",
    "Redes sociais cujo nome tem exatamente duas sílabas",
    "Redes sociais cujo nome termina com a letra A",
    "Redes sociais cujo nome termina com a letra O",
    "Redes sociais cujo nome contém a letra Z",
    "Redes sociais cujo nome contém a letra C",
    "Redes sociais cujo nome tem acento gráfico",
    "Redes sociais cujo nome é uma palavra composta",
    "Redes sociais considerados clássicos (criados há mais de 20 anos)",
    "Redes sociais lançados ou populares nos últimos 10 anos",
    "Partes do corpo cujo nome começa com vogal",
    "Partes do corpo cujo nome começa com consoante",
    "Partes do corpo cujo nome tem mais de 8 letras",
    "Partes do corpo cujo nome tem menos de 5 letras",
    "Partes do corpo cujo nome tem exatamente duas sílabas",
    "Partes do corpo cujo nome termina com a letra A",
    "Partes do corpo cujo nome termina com a letra O",
    "Partes do corpo cujo nome contém a letra Z",
    "Partes do corpo cujo nome contém a letra C",
    "Partes do corpo cujo nome tem acento gráfico",
    "Partes do corpo cujo nome é uma palavra composta",
    "Partes do corpo considerados grandes ou pesados",
    "Partes do corpo considerados pequenos ou leves",
    "Ossos do corpo cujo nome começa com vogal",
    "Ossos do corpo cujo nome começa com consoante",
    "Ossos do corpo cujo nome tem mais de 8 letras",
    "Ossos do corpo cujo nome tem menos de 5 letras",
    "Ossos do corpo cujo nome tem exatamente duas sílabas",
    "Ossos do corpo cujo nome termina com a letra A",
    "Ossos do corpo cujo nome termina com a letra O",
    "Ossos do corpo cujo nome contém a letra Z",
    "Ossos do corpo cujo nome contém a letra C",
    "Ossos do corpo cujo nome tem acento gráfico",
    "Ossos do corpo cujo nome é uma palavra composta",
    "Ossos do corpo considerados grandes ou pesados",
    "Ossos do corpo considerados pequenos ou leves",
    "Cores cujo nome começa com vogal",
    "Cores cujo nome começa com consoante",
    "Cores cujo nome tem mais de 8 letras",
    "Cores cujo nome tem menos de 5 letras",
    "Cores cujo nome tem exatamente duas sílabas",
    "Cores cujo nome termina com a letra A",
    "Cores cujo nome termina com a letra O",
    "Cores cujo nome contém a letra Z",
    "Cores cujo nome contém a letra C",
    "Cores cujo nome tem acento gráfico",
    "Cores cujo nome é uma palavra composta",
    "Formas geométricas cujo nome começa com vogal",
    "Formas geométricas cujo nome começa com consoante",
    "Formas geométricas considerados grandes ou pesados",
    "Formas geométricas considerados pequenos ou leves",
    "Feriados brasileiros cujo nome começa com vogal",
    "Feriados brasileiros cujo nome começa com consoante",
    "Feriados brasileiros cujo nome tem mais de 8 letras",
    "Feriados brasileiros cujo nome tem menos de 5 letras",
    "Feriados brasileiros cujo nome tem exatamente duas sílabas",
    "Feriados brasileiros cujo nome termina com a letra A",
    "Feriados brasileiros cujo nome termina com a letra O",
    "Feriados brasileiros cujo nome contém a letra Z",
    "Feriados brasileiros cujo nome contém a letra C",
    "Feriados brasileiros cujo nome tem acento gráfico",
    "Feriados brasileiros cujo nome é uma palavra composta",
    "Elementos químicos cujo nome começa com vogal",
    "Elementos químicos cujo nome começa com consoante",
    "Elementos químicos cujo nome tem mais de 8 letras",
    "Elementos químicos cujo nome tem menos de 5 letras",
    "Elementos químicos cujo nome termina com a letra O",
    "Idiomas cujo nome começa com vogal",
    "Idiomas cujo nome começa com consoante",
    "Idiomas cujo nome tem mais de 8 letras",
    "Idiomas cujo nome tem menos de 5 letras",
    "Idiomas cujo nome tem exatamente duas sílabas",
    "Idiomas cujo nome termina com a letra A",
    "Idiomas cujo nome termina com a letra O",
    "Idiomas cujo nome contém a letra Z",
    "Idiomas cujo nome contém a letra C",
    "Idiomas cujo nome tem acento gráfico",
    "Idiomas cujo nome é uma palavra composta",
    "Idiomas de origem ou fabricação brasileira",
    "Idiomas de origem ou fabricação europeia",
    "Idiomas de origem ou fabricação asiática",
    "Idiomas de origem ou fabricação norte-americana",
    "Museus cujo nome começa com vogal",
    "Museus cujo nome começa com consoante",
    "Museus cujo nome tem mais de 8 letras",
    "Museus cujo nome tem menos de 5 letras",
    "Museus cujo nome tem exatamente duas sílabas",
    "Museus cujo nome termina com a letra A",
    "Museus cujo nome termina com a letra O",
    "Museus cujo nome contém a letra Z",
    "Museus cujo nome contém a letra C",
    "Museus cujo nome tem acento gráfico",
    "Museus cujo nome é uma palavra composta"
  ]
}


# --- PROIBIDO (100+ items) ---
proibido = []

words_list = [
    # Animais
    ("Gato", ["Miar", "Animal", "Rato", "Leite", "Felino"]),
    ("Cachorro", ["Latir", "Osso", "Animal", "Melhor amigo", "Mordida"]),
    ("Elefante", ["Tromba", "Grande", "África", "Peso", "Marfim"]),
    ("Leão", ["Rei", "Selva", "Rugido", "Juba", "Carnívoro"]),
    ("Tigre", ["Listras", "Feroz", "Gato", "Asiático", "Laranja"]),
    ("Macaco", ["Banana", "Árvore", "Pular", "Gorila", "Chimpanzé"]),
    ("Urso", ["Mel", "Inverno", "Hibernar", "Polar", "Pardo"]),
    ("Coelho", ["Cenoura", "Orelhas", "Pular", "Páscoa", "Rápido"]),
    ("Pássaro", ["Voar", "Asas", "Pena", "Ninho", "Céu"]),
    ("Peixe", ["Água", "Nadar", "Mar", "Aquário", "Escamas"]),
    ("Tubarão", ["Mar", "Dentes", "Perigo", "Sangue", "Filme"]),
    ("Baleia", ["Oceano", "Enorme", "Mamífero", "Água", "Azul"]),
    ("Cavalo", ["Cavalgar", "Sela", "Fazenda", "Relinchar", "Crina"]),
    ("Galinha", ["Ovo", "Pena", "Fazenda", "Cacarejar", "Galo"]),
    ("Vaca", ["Leite", "Muu", "Fazenda", "Pasto", "Queijo"]),
    ("Porco", ["Lama", "Rosa", "Bacon", "Fazenda", "Gordo"]),
    ("Cobra", ["Veneno", "Rastejar", "Picar", "Língua", "Cascavel"]),
    ("Aranha", ["Teia", "Inseto", "Oito patas", "Picar", "Medo"]),
    ("Sapo", ["Pular", "Verde", "Brejo", "Língua", "Mosca"]),
    ("Jacaré", ["Lagoa", "Dentes", "Couro", "Réptil", "Boca"]),
    
    # Comidas
    ("Maçã", ["Fruta", "Branca de Neve", "Vermelha", "Árvore", "Comer"]),
    ("Banana", ["Macaco", "Amarela", "Casca", "Fruta", "Comer"]),
    ("Laranja", ["Suco", "Fruta", "Cor", "Vitamina C", "Cítrica"]),
    ("Uva", ["Vinho", "Roxa", "Cacho", "Fruta", "Suco"]),
    ("Morango", ["Vermelho", "Fruta", "Semente", "Doce", "Bolo"]),
    ("Melancia", ["Verde", "Vermelha", "Grande", "Fruta", "Caroço"]),
    ("Pizza", ["Massa", "Queijo", "Italiana", "Redonda", "Forno"]),
    ("Hambúrguer", ["Pão", "Carne", "Fast food", "Sanduíche", "Queijo"]),
    ("Batata Frita", ["Óleo", "Salgada", "Ketchup", "Fast food", "McDonalds"]),
    ("Sorvete", ["Gelado", "Doce", "Casquinha", "Sabor", "Verão"]),
    ("Chocolate", ["Cacau", "Doce", "Marrom", "Páscoa", "Derreter"]),
    ("Bolo", ["Aniversário", "Festa", "Vela", "Fatia", "Doce"]),
    ("Pão", ["Padaria", "Manteiga", "Trigo", "Comer", "Francês"]),
    ("Queijo", ["Leite", "Rato", "Amarelo", "Minas", "Comer"]),
    ("Arroz", ["Feijão", "Branco", "Grão", "Panela", "Comida"]),
    ("Feijão", ["Arroz", "Marrom", "Preto", "Caldo", "Panela"]),
    ("Macarrão", ["Massa", "Molho", "Espaguete", "Italiano", "Comer"]),
    ("Sopa", ["Quente", "Colher", "Caldo", "Frio", "Legumes"]),
    ("Salada", ["Alface", "Tomate", "Verde", "Saudável", "Dieta"]),
    ("Churrasco", ["Carne", "Fogo", "Fim de semana", "Espeto", "Carvão"]),
    
    # Objetos
    ("Mesa", ["Cadeira", "Madeira", "Comer", "Sentar", "Móvel"]),
    ("Cadeira", ["Sentar", "Mesa", "Pernas", "Móvel", "Costas"]),
    ("Sofá", ["Sala", "Sentar", "Televisão", "Descansar", "Confortável"]),
    ("Cama", ["Dormir", "Quarto", "Colchão", "Travesseiro", "Deitar"]),
    ("Geladeira", ["Frio", "Comida", "Cozinha", "Gelo", "Guardar"]),
    ("Fogão", ["Fogo", "Cozinhar", "Panela", "Cozinha", "Gás"]),
    ("Televisão", ["Assistir", "Tela", "Controle", "Sala", "Canal"]),
    ("Computador", ["Internet", "Teclado", "Mouse", "Tela", "Trabalho"]),
    ("Celular", ["Ligar", "Telefone", "Tela", "Mensagem", "Internet"]),
    ("Relógio", ["Hora", "Tempo", "Pulso", "Ponteiro", "Minuto"]),
    ("Óculos", ["Olho", "Enxergar", "Lente", "Rosto", "Míope"]),
    ("Espelho", ["Reflexo", "Rosto", "Vidro", "Quebrar", "Ver"]),
    ("Livro", ["Ler", "Páginas", "História", "Papel", "Biblioteca"]),
    ("Caderno", ["Escrever", "Escola", "Folha", "Anotar", "Caneta"]),
    ("Caneta", ["Escrever", "Tinta", "Papel", "Lápis", "Azul"]),
    ("Lápis", ["Escrever", "Borracha", "Grafite", "Papel", "Apontador"]),
    ("Borracha", ["Apagar", "Lápis", "Erro", "Escola", "Papel"]),
    ("Tesoura", ["Cortar", "Papel", "Lâmina", "Cabeleireiro", "Ferramenta"]),
    ("Faca", ["Cortar", "Cozinha", "Comida", "Garfo", "Afiada"]),
    ("Garfo", ["Faca", "Comer", "Cozinha", "Dentes", "Talher"]),
    ("Colher", ["Sopa", "Comer", "Sobremesa", "Talher", "Cozinha"]),
    ("Prato", ["Comida", "Comer", "Mesa", "Vidro", "Cozinha"]),
    ("Copo", ["Beber", "Água", "Vidro", "Suco", "Boca"]),
    ("Chave", ["Porta", "Abrir", "Fechadura", "Carro", "Casa"]),
    ("Dinheiro", ["Comprar", "Banco", "Nota", "Moeda", "Rico"]),
    ("Carteira", ["Dinheiro", "Documento", "Bolso", "Guardar", "Cartão"]),
    ("Bolsa", ["Mulher", "Carregar", "Ombro", "Guardar", "Mochila"]),
    ("Mochila", ["Costas", "Escola", "Carregar", "Caderno", "Viagem"]),
    ("Guarda-chuva", ["Chuva", "Água", "Proteger", "Abrir", "Molhar"]),
    ("Toalha", ["Banho", "Secar", "Água", "Corpo", "Rosto"]),
    
    # Lugares
    ("Praia", ["Areia", "Mar", "Sol", "Verão", "Onda"]),
    ("Escola", ["Estudar", "Professor", "Aluno", "Aula", "Caderno"]),
    ("Hospital", ["Médico", "Doente", "Enfermeira", "Saúde", "Remédio"]),
    ("Cinema", ["Filme", "Pipoca", "Tela", "Escuro", "Assistir"]),
    ("Parque", ["Brincar", "Árvore", "Grama", "Criança", "Ao ar livre"]),
    ("Igreja", ["Rezar", "Deus", "Missa", "Padre", "Religião"]),
    ("Banco", ["Dinheiro", "Sacar", "Conta", "Fila", "Cartão"]),
    ("Supermercado", ["Comprar", "Comida", "Carrinho", "Prateleira", "Caixa"]),
    ("Farmácia", ["Remédio", "Comprar", "Doente", "Saúde", "Receita"]),
    ("Padaria", ["Pão", "Comprar", "Manteiga", "Doce", "Leite"]),
    ("Restaurante", ["Comer", "Garçom", "Comida", "Mesa", "Conta"]),
    ("Aeroporto", ["Avião", "Viajar", "Mala", "Passagem", "Voo"]),
    ("Rodoviária", ["Ônibus", "Viajar", "Passagem", "Mala", "Estação"]),
    ("Shopping", ["Lojas", "Comprar", "Passear", "Praça de alimentação", "Cinema"]),
    ("Academia", ["Malhar", "Peso", "Exercício", "Músculo", "Suor"]),
    
    # Natureza / Diversos
    ("Sol", ["Calor", "Dia", "Amarelo", "Céu", "Queimar"]),
    ("Lua", ["Noite", "Céu", "Branca", "Estrela", "Lobisomem"]),
    ("Estrela", ["Céu", "Noite", "Brilhar", "Espaço", "Sol"]),
    ("Nuvem", ["Céu", "Chuva", "Branca", "Algodão", "Alto"]),
    ("Chuva", ["Água", "Cair", "Molhar", "Céu", "Nuvem"]),
    ("Vento", ["Ar", "Soprar", "Forte", "Frio", "Brisa"]),
    ("Neve", ["Frio", "Branco", "Gelo", "Inverno", "Boneco"]),
    ("Fogo", ["Queimar", "Quente", "Chama", "Incêndio", "Fumaça"]),
    ("Água", ["Beber", "Líquido", "Sede", "Molhar", "Rio"]),
    ("Terra", ["Chão", "Planeta", "Plantar", "Sujeira", "Marrom"]),
    ("Árvore", ["Planta", "Folha", "Madeira", "Verde", "Raiz"]),
    ("Flor", ["Pétala", "Jardim", "Cheiro", "Rosa", "Planta"]),
    ("Música", ["Tocar", "Ouvir", "Cantar", "Som", "Banda"]),
    ("Festa", ["Música", "Dança", "Comemorar", "Bolo", "Bebida"]),
    ("Casamento", ["Noiva", "Festa", "Igreja", "Aliança", "Amor"]),
]

for word, forb in words_list:
    proibido.append({"word": word, "forbidden": forb})

# Impostor
impostor = [
    "Qual é a sua relação com isso?",
    "Onde você costuma encontrar isso?",
    "Quando foi a última vez que você viu ou usou isso?",
    "Que cor ou forma isso costuma ter?",
    "Se você pudesse descrever isso em uma palavra, qual seria?",
    "Qual o tamanho aproximado disso?",
    "Isso é mais usado por adultos ou crianças?",
    "Isso faz algum tipo de barulho?",
    "Você acha que isso é algo caro ou barato?",
    "Você levaria isso para uma viagem?"
]

# Preserve 'nota'
nota = []
if os.path.exists('data/perguntas.json'):
    with open('data/perguntas.json', 'r', encoding='utf-8') as f:
        old_data = json.load(f)
        nota = old_data.get('nota', [])

data = {
    "palpite": palpite,
    "duvido": duvido,
    "proibido": proibido,
    "impostor": impostor,
    "nota": nota
}

os.makedirs('data', exist_ok=True)
with open('data/perguntas.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Generated {len(palpite)} palpite, {len(duvido)} duvido, {len(proibido)} proibido items.")
